#![allow(dead_code)]
#![allow(clippy::missing_errors_doc)]

use std::fs;

use serde::Deserialize;

const ENDPOINTS_FILE: &str = "target/kurtosis-endpoints.json";

/// A single EL endpoint entry from the JSON file.
#[derive(Debug, Clone, Deserialize)]
pub struct ElEndpoint {
    pub client: String,
    pub http: String,
    pub ws: Option<String>,
}

/// Load Execution Layer (EL) endpoints from the JSON file generated by `scripts/setup-kurtosis.sh`.
///
/// The script must be run before the tests to populate `target/kurtosis-endpoints.json`.
///
/// # Example
///
/// ```bash
/// ./scripts/setup-kurtosis.sh
/// cargo test --features integration
/// ```
pub fn load_el_endpoints() -> anyhow::Result<Vec<ElEndpoint>> {
    let content = fs::read_to_string(ENDPOINTS_FILE).map_err(|e| {
        anyhow::anyhow!(
            "Failed to read '{ENDPOINTS_FILE}': {e}\n\n\
            Run './scripts/setup-kurtosis.sh <enclave>' first to generate the endpoints file."
        )
    })?;

    let endpoints: Vec<ElEndpoint> = serde_json::from_str(&content)
        .map_err(|e| anyhow::anyhow!("Failed to parse '{ENDPOINTS_FILE}': {e}"))?;

    if endpoints.is_empty() {
        anyhow::bail!("No EL endpoints found in '{ENDPOINTS_FILE}'");
    }

    Ok(endpoints)
}
