name: tests

permissions:
  contents: read

on:
  pull_request:
  merge_group:
  push:
    branches: [main]

env:
  CARGO_TERM_COLOR: always

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  cargo-next-test:
    name: Cargo test
    runs-on: ubuntu-latest

    steps:
      - name: Harden the runner (Audit all outbound calls)
        uses: step-security/harden-runner@5ef0c079ce82195b2a36a210272d6b661572d83e # v2.14.2
        with:
          egress-policy: audit

      - name: Fetch Repository
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd

      - name: Install stable toolchain
        uses: actions-rust-lang/setup-rust-toolchain@1780873c7b576612439a134613cc4cc74ce5538c # v1.15.2

      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@8789b3e21e6c11b2697f5eb56eddae542f746c10 # v1.7.0

      - name: Cache cargo-nextest binary
        id: cache-cargo-nextest
        uses: actions/cache@cdf6c1fa76f9f475f3d7449005a359c84ca0f306 # v5.0.3
        with:
          path: ~/.cargo/bin/cargo-nextest
          key: ${{ runner.os }}-cargo-nextest-${{ hashFiles('**/Cargo.lock') }}

      - name: Install cargo-nextest
        if: steps.cache-cargo-nextest.outputs.cache-hit != 'true'
        uses: taiki-e/install-action@d4422f254e595ee762a758628fe4f16ce050fa2e # v2.67.28
        with:
          tool: cargo-nextest

      - name: Cargo test
        run: cargo nextest run --locked --all-targets --all-features --no-tests=pass --no-fail-fast

        # https://github.com/rust-lang/cargo/issues/6669
      - name: Run doc tests
        run: cargo test --locked --doc --all-features --no-fail-fast
